### ISSUE TITLE
Navigate button overlay

### ISSUE THREAD

**Issue by TYZRPVX** [DonkeyPacific/obsidian-full-screen-cross-platform-plugin#7]
<img width="225" alt="image" src="https://github.com/DonkeyPacific/obsidian-full-screen-cross-platform-plugin/assets/7645818/b1adc4bb-aa25-4359-ae17-0e1402c7a756">

awesome plugin, but remain some ui issue

**Comment by DonkeyPacific** [comment]
You can exit the full screen mode and then click the overlay button,
